### ISSUE TITLE
babel-node

### ISSUE THREAD

**Issue by dcsan** [fibo/SVGx#17]
I know this is an old project but wondering should i install babel-node globally to run this? 
I tried that but it doesn't seem to work anyway...

is there a more updated project evolved from this you might recommend for server side SVG in 2021 ?

**Comment by fibo** [comment]
hi @dcsan sorry I do not have time right now to update the package (I am working hard on a algo trading website side project, that will use dataflow programming to create strategies with nodes graphically ^:). Actually I tryed but it takes more than a 🍅 ...

basically, this package is just a thin wrapper around react static rendering. It just adds a doctype

it should be pretty straightforward to do it (no more than 1 day)

**Comment by dcsan** [comment]
ok thanks for the reply.
