### ISSUE TITLE
Question: SVG Client-Side methods available?

### ISSUE THREAD

**Issue by fabianmu** [fibo/SVGx#6]
Hi fibo,
Wondering wether SVG Client-Side methods like `getTotalLength`, `getBBox` etc. are available and if so, how they may be called in SVGx or the underlying reactDom?
Thanks, Fabian

**Comment by fibo** [comment]
Hi,

I am afraid they are not supported, for example you could use them in a `componentDidMount` method, but you would need a server side implementation which, as far as I know is not a React feature.

**Comment by fibo** [comment]
@fabianmu I am closing this issue, since it would be really difficult to polifill those features server side.
